/* Isolated release smoke test. NEVER point this script at production. */
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const { PrismaClient } = require('../../packages/db/node_modules/@prisma/client')
const target = new URL(process.env.DATABASE_URL || 'http://invalid')
assert(process.env.CBC_CATALOG_SMOKE === '1' && ['localhost', '127.0.0.1'].includes(target.hostname) && target.pathname === '/cbc_test', 'Smoke test is restricted to the isolated local cbc_test database.')
const base = 'http://127.0.0.1:3000'
const db = new PrismaClient()
async function main() {
  const settings = { wholesale_markup_pct: '20', MIN_QTY_PER_METHOD: '10', MIN_PRODUCTION_DAYS: '15', RUSH_MIN_PRODUCTION_DAYS: '5', IVA_PCT: '16' }
  for (const [key, value] of Object.entries(settings)) await db.setting.upsert({ where: { key }, create: { key, value }, update: { value } })
  const zone = await db.shippingZone.create({ data: { name: 'CDMX / Área Metropolitana', active: true, baseFee: 0, feePerUnit: 15 } })
  const images = []
  for (const name of ['v60.png', 'prensa-francesa-plastico-v2.png']) {
    const image = await fs.readFile(path.join('assets/catalog-samples', name))
    const upload = await fetch(`${base}/api/upload?folder=qa&filename=${name}&type=image/png`, { method: 'POST', headers: { 'Content-Type': 'image/png' }, body: image })
    assert.equal(upload.status, 200)
    images.push((await upload.json()).publicUrl)
  }
  const extra = await db.extra.create({ data: { id: 'qa-catalog-filters', slug: 'qa-paquetes-100', name: 'Filtros · prueba de catálogo', unitPrice: 100, images, imageUrl: images[0], shortDescription: 'Ficha de prueba: presentación por paquete.', description: 'PRUEBA DE CATÁLOGO. Estas imágenes son referencias de prueba, no fotografías de los filtros.\n\nPaquete de 100 piezas.\n\nDescripción extendida para verificar que la ficha conserva los párrafos y toda la información.', unitLabel: 'paquete', unitsPerPack: 100, minQty: 5 } })
  await db.extra.create({ data: { id: 'qa-hidden', name: 'Oculto QA', unitPrice: 1, catalogVisible: false } })
  await db.extra.create({ data: { id: 'qa-inactive', name: 'Inactivo QA', unitPrice: 1, active: false } })
  for (const route of ['/catalogo-b2b', `/catalogo-b2b/extra/${extra.slug}`, '/cotizar', `/cotizar?extra=${extra.id}&qty=50`, '/en/catalogo-b2b', `/en/catalogo-b2b/extra/${extra.id}`]) {
    const response = await fetch(base + route, { redirect: 'manual' })
    assert.equal(response.status, 200, route)
  }
  assert.equal((await fetch(base + '/catalogo-b2b/extra/qa-hidden')).status, 404)
  assert.equal((await fetch(base + '/catalogo-b2b/extra/qa-inactive')).status, 404)
  const input = { items: [], extras: [{ extraId: extra.id, qty: 50 }], shippingZoneId: zone.id, rush: false }
  const post = (route, data) => fetch(base + route, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) })
  const calculated = await post('/api/quote/calculate', { ...input, total: 1 })
  assert.equal(calculated.status, 200)
  assert.equal((await calculated.json()).total, 7830)
  assert.equal((await post('/api/quote/calculate', { ...input, extras: [] })).status, 400)
  const saved = await post('/api/quote/submit', { ...input, companyName: 'QA', contactName: 'QA', email: 'qa@example.invalid', whatsapp: '5550000000', total: 1 })
  assert.equal(saved.status, 200)
  const quote = await db.quote.findUniqueOrThrow({ where: { id: (await saved.json()).quoteId } })
  assert.equal(quote.total, 7830)
  assert.deepEqual(quote.items, [])
  assert.equal(quote.extraItems[0].qty, 50)
  assert.equal(quote.extraItems[0].unitsPerPack, 100)
  assert.equal(quote.extraItems[0].unitLabel, 'paquete')
  if (process.env.PLAYWRIGHT_MODULE) {
    const { chromium } = require(process.env.PLAYWRIGHT_MODULE)
    const browser = await chromium.launch({ headless: true })
    try {
      const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } })
      await page.goto(base + `/catalogo-b2b/extra/${extra.slug}`)
      await page.getByRole('heading', { name: extra.name, exact: true }).waitFor()
      await page.screenshot({ path: '/tmp/cbc-catalog-desktop.png' })
      await page.getByRole('spinbutton').fill('50')
      await page.getByRole('link', { name: 'Cotizar este producto' }).click()
      await page.getByRole('spinbutton', { name: `Cantidad de ${extra.name}` }).waitFor()
      assert.equal(await page.getByRole('spinbutton', { name: `Cantidad de ${extra.name}` }).inputValue(), '50')
      await page.getByRole('button', { name: 'Siguiente', exact: true }).click()
      await page.getByRole('button', { name: 'Siguiente', exact: true }).click()
      await page.getByPlaceholder('Tu empresa').fill('Empresa QA navegador')
      await page.getByPlaceholder('Tu nombre').fill('QA Navegador')
      await page.getByPlaceholder('correo@ejemplo.com').fill('browser@example.invalid')
      await page.getByPlaceholder('+52 555 123 4567').fill('5550000001')
      await page.getByRole('button', { name: 'Enviar cotización', exact: true }).click()
      await page.getByRole('heading', { name: '¡Cotización enviada!' }).waitFor()
      const browserQuote = await db.quote.findFirstOrThrow({ where: { customer: { whatsapp: '5550000001' } } })
      assert.deepEqual(browserQuote.items, [])
      assert.equal(browserQuote.extraItems[0].qty, 50)
      const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true })
      await mobile.goto(base + '/catalogo-b2b')
      await mobile.getByRole('searchbox').fill('Filtros')
      assert(await mobile.getByRole('link', { name: 'Ver detalles', exact: true }).count() >= 1)
      assert(await mobile.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Catalog overflows mobile viewport')
      await mobile.screenshot({ path: '/tmp/cbc-catalog-mobile.png' })
      // Admin validation uses only a test identity signed with the isolated CI secret.
      const { encode } = require('../../apps/web/node_modules/next-auth/jwt')
      const admin = await db.user.create({ data: { email: 'admin-qa@example.invalid', name: 'Catalog QA', active: true, isSuperadmin: true } })
      const token = await encode({ secret: process.env.NEXTAUTH_SECRET, token: { sub: admin.id, dbUserId: admin.id, email: admin.email, name: admin.name, isSuperadmin: true, role: 'admin' }, maxAge: 600 })
      const adminContext = await browser.newContext({ viewport: { width: 1920, height: 1080 } })
      await adminContext.addCookies([{ name: 'next-auth.session-token', value: token, url: base, httpOnly: true, sameSite: 'Lax' }])
      const editor = await adminContext.newPage()
      editor.on('pageerror', error => console.error('Admin browser error:', error))
      await editor.goto(base + '/admin/sales/extras')
      await editor.getByRole('heading', { name: 'Extras y catálogo B2B' }).waitFor()
      await editor.locator('article').filter({ hasText: extra.name }).getByRole('button', { name: 'Editar', exact: true }).click()
      await editor.getByRole('heading', { name: 'Editar ficha', exact: true }).waitFor()
      await editor.getByRole('heading', { name: 'Editar ficha', exact: true }).scrollIntoViewIfNeeded()
      await editor.screenshot({ path: '/tmp/cbc-catalog-admin.png' })
      const description = 'Descripción extendida guardada desde el navegador.\n\nSegundo párrafo con características del paquete de prueba.'
      await editor.getByLabel('Descripción completa', { exact: true }).fill(description)
      await editor.getByLabel('Costo unitario (sin IVA)', { exact: true }).fill('100.25')
      await editor.getByRole('button', { name: 'Mover fotografía 2 antes', exact: true }).click()
      assert(await editor.locator('form').evaluate(form => form.checkValidity()), 'Admin editor rejects a valid decimal cost')
      await editor.getByRole('button', { name: 'Guardar cambios', exact: true }).click()
      await editor.getByRole('status').filter({ hasText: 'Extra guardado.' }).waitFor()
      const edited = await db.extra.findUniqueOrThrow({ where: { id: extra.id } })
      assert.equal(edited.description, description)
      assert.equal(edited.unitPrice, 100.25)
      assert.equal(edited.images[0], images[1])
      assert.equal(edited.imageUrl, images[1])
      await adminContext.close()
    } finally { await browser.close() }
  }
  console.log('PASS: catalog routes, visibility, isolated extras-only calculation/save, package snapshots, browser quote flow, mobile layout and authenticated admin editing.')
}
main().catch(error => { console.error(error); process.exitCode = 1 }).finally(() => db.$disconnect())
